import Image from "next/image";
import Link from "next/link";
import { ShieldCheck, HeartPulse, Handshake, ArrowRight } from "lucide-react";
import { products } from "@/data/site";
import { formatNaira } from "@/lib/store";
import { AddToCartButton } from "@/components/cart/AddToCartButton";
export function PageHero({eyebrow,title,text}:{eyebrow?:string;title:string;text:string}){return <section className="page-hero"><div className="container narrow">{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{text}</p></div></section>}
export function ProductGrid(){return <div className="product-grid">{products.map(p=><article className={`product-card ${p.accent}`} key={p.slug}><Link href={`/products/${p.slug}`} className="product-image-wrap"><Image src={p.image} alt={`${p.name} product pack`} fill sizes="(max-width: 700px) 90vw, (max-width: 1100px) 45vw, 25vw" className="product-image"/></Link><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><p>{p.summary}</p><strong className="product-price">{formatNaira(p.priceKobo)}</strong><div className="product-card-actions"><AddToCartButton slug={p.slug} name={p.name} priceKobo={p.priceKobo}/><Link className="text-link" href={`/products/${p.slug}`}>Details <ArrowRight size={17}/></Link></div></article>)}</div>}
export function TrustCards(){const items=[[ShieldCheck,"Quality First","Quality-focused processes and responsible product information."],[HeartPulse,"People-Centred","Healthcare solutions designed around real everyday needs."],[Handshake,"Trusted Partnerships","Long-term relationships with healthcare and distribution partners."]] as const;return <div className="three-grid">{items.map(([Icon,t,x])=><article className="icon-card" key={t}><Icon/><h3>{t}</h3><p>{x}</p></article>)}</div>}
export function CTA(){return <section className="cta"><div className="container cta-inner"><div><span className="eyebrow">Connect with Bridgecare</span><h2>Let’s improve healthcare access together.</h2></div><div className="cta-actions"><Link className="button light-button" href="/contact">Contact us</Link><Link className="button outline-light" href="/distributors">Partner with us</Link></div></div></section>}
